#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f challenge.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace challenge.sv --exe challenge_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vchallenge.mk Vchallenge

# run executable simulation file
obj_dir/Vchallenge